### ISSUE TITLE
UnsatisfiedLinkError: error initializing public namespace: "libdreamland.so" was not found in the default namespace

### ISSUE THREAD

**Issue by canyie** [canyie/Dreamland#2]
问题：安装Dreamland后，大部分应用闪退
logcat：
```
02-05 11:10:44.888 15784 15784 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Unable to create namespace for the classloader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/ViPER4AndroidFX/ViPER4AndroidFX.apk"],nativeLibraryDirectories=[/system/priv-app/ViPER4AndroidFX/lib/arm, /system/fake-libs, /system/priv-app/ViPER4AndroidFX/ViPER4AndroidFX.apk!/lib/armeabi, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]]: android_init_namespaces failed: error initializing public namespace: "libdreamland.so" was not found in the default namespace
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:54)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:540)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.LoadedApk.getClassLoader(LoadedApk.java:573)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1993)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.LoadedApk.getResources(LoadedApk.java:799)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.ContextImpl.<init>(ContextImpl.java:2218)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:2163)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5618)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:156)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6595)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
02-05 11:10:44.888 15784 15784 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

设备信息：
HuaWei Honor DUK-AL20
Android 7.0
装了Xposed

**Comment by canyie** [comment]
重新实现了注入逻辑，避免修改public.libraries.txt，不会遇到这个问题了。
